jobs:
- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows\CMake With SonarCloud
  pool:
    vmImage: 'windows-latest'
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud' # Name of the SonarCloud service connection you created
      organization: 'sc-sq-c-family-examples'
      scannerMode: 'CLI'
      configMode: 'file'
  - bash: |
      mkdir -p $HOME/.sonar
      curl -sSLo $HOME/.sonar/build-wrapper-win-x86.zip ${{variables.BUILD_WRAPPER_DOWNLOAD_URL}}
      unzip -o $HOME/.sonar/build-wrapper-win-x86.zip -d $HOME/.sonar/
    displayName: Download and install build wrapper
  - bash: |
      mkdir build
      cmake -S . -B build
      autoreconf --install
      ./configure
      $HOME/.sonar/build-wrapper-win-x86-64 --out-dir build_wrapper_output_directory make clean all
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarCloudAnalyze@1
